spring:
  profiles:
    active: uat
  session:
    store-type: none #redis
#  redis:
#    database: 0
#    port: 6369
#    host: 127.0.0.1
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    timeout: 5000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzh.shortvideohub.pojo
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

---
spring:
  profiles: uat
server:
  port: 9250
  servlet:
    context-path: /v3
---
spring:
  profiles: dev
server:
  port: 9250
  servlet:
    context-path: /v3
---
spring:
  profiles: prod
server:
  port: 9025
  servlet:
    context-path: /v3



