spring:
  datasource:
    diverClassNmae: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_video_db?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 80
        max-wait: -1
        min-idle: 1
    timeout: 5000ms