spring:
  datasource:
    diverClassNmae: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.126.82.137:3306/short_video_db?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: short_video_db
    password: root

  redis:
    host: 112.126.82.137
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 80
        max-wait: -1
        min-idle: 1
    timeout: 5000ms

fileUrl:
  videoFileUrl: "D:/sv_files/video/"
  coverFileUrl: "D:/sv_files/cover/"
  avatarFileUrl: "D:/sv_files/avatar/"

VideoFileUrl: "D:/sv_files/video/"
CoverFileUrl: "D:/sv_files/cover/"

initData:
  password: "123456"

task:
  fnsAttentionsNumUpdate:
    cron: "0 0 0 * * ? "
  videoLikesCommentsNumUpdate:
    cron: "0 0 1 * * ? "
  videoHot:
    cron: "0 0 1/1 * * ? "

logging:
  path: "D"